# Generated by Django 2.1.7 on 2019-03-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='language',
            name='used_on',
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.ManyToManyField(to='rate.Language'),
        ),
    ]
