# Generated by Django 2.1.7 on 2019-03-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='review',
            field=models.CharField(default='', max_length=140),
        ),
    ]
