# Generated by Django 2.1.7 on 2019-03-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20190316_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.CharField(default='#', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='github',
            field=models.CharField(default='#', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.CharField(default='#', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter',
            field=models.CharField(default='#', max_length=70, null=True),
        ),
    ]
