# Generated by Django 2.1.7 on 2019-03-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_contact_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='review',
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.CharField(default='', max_length=140),
        ),
    ]
